/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'explanation' : IDL.Text,
  'answerOptions' : IDL.Vec(IDL.Text),
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'questionId' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'createQuestion' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getQuestionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'initializeDefaultQuestions' : IDL.Func([], [], []),
  'updateQuestion' : IDL.Func([IDL.Nat, Question], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'explanation' : IDL.Text,
    'answerOptions' : IDL.Vec(IDL.Text),
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'questionId' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'createQuestion' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getQuestionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'initializeDefaultQuestions' : IDL.Func([], [], []),
    'updateQuestion' : IDL.Func([IDL.Nat, Question], [], []),
  });
};

export const init = ({ IDL }) => { return []; };