/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Question {
  'explanation' : string,
  'answerOptions' : Array<string>,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'questionId' : bigint,
  'category' : string,
}
export interface _SERVICE {
  'createQuestion' : ActorMethod<
    [string, Array<string>, bigint, string, string],
    bigint
  >,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getQuestion' : ActorMethod<[bigint], Question>,
  'getQuestionsByCategory' : ActorMethod<[string], Array<Question>>,
  'initializeDefaultQuestions' : ActorMethod<[], undefined>,
  'updateQuestion' : ActorMethod<[bigint, Question], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];